package com.report.sender.util;

public enum ServiceName {
    ACCOUNT_DATA_DELEGATE,
    CALCULATE_FOOD_DELEGATE,
    CALCULATE_LABOR_DELEGATE,
    CALCULATE_VAT_DELEGATE,
    SEND_REPORT_MESSAGE_DELEGATE
}
